### ISSUE TITLE
Tests don't compile if ORM is disabled

### ISSUE THREAD

**Issue by SchaichAlonso** [silverqx/TinyORM#16] opened 2023-07-24 11:47 UTC
The querybuilders' unit tests fail to compile if ORM compilation is disabled via cmake

    PS D:\projects\TinyORM> git reflog -n 1
        1cc4dd18 (HEAD -> main, origin/main, origin/develop, origin/HEAD) HEAD@{0}: pull: Fast-forward
    PS D:\projects\TinyORM> cmake -B build -DORM=off -DBUILD_TESTS=on "-DCMAKE_TOOLCHAIN_FILE=d:/vcpkg/scripts/buildsystems/vcpkg.cmake" .
    PS D:\projects\TinyORM> cmake --build build
        [...]
    D:\Projects\TinyORM\tests\auto\unit\orm\schema\mysql_schemabuilder\tst_mysql_schemabuilder.cpp(31,24): error C2039: 'LogicError': is not a member of 'Orm::Exceptions' [D:\Projects\TinyORM\build\tests\auto\unit\orm\schema\mysql_schemabuilder\mysql_schemabuilder.vcxproj]
    D:\Projects\TinyORM\include\orm/exceptions/queryerror.hpp(16,11): message : see declaration of 'Orm::Exceptions' [D:\Projects\TinyORM\build\tests\auto\unit\orm\schema\mysql_schemabuilder\mysql_schemabuilder.vcxproj]
    D:\Projects\TinyORM\tests\auto\unit\orm\schema\mysql_schemabuilder\tst_mysql_schemabuilder.cpp(31,1): error C2873: 'LogicError': symbol cannot be used in a using-declaration [D:\Projects\TinyORM\build\tests\auto\unit\orm\schema\mysql_schemabuilder\mysql_schemabuilder.vcxproj]
    D:\Projects\TinyORM\tests\auto\unit\orm\schema\mysql_schemabuilder\tst_mysql_schemabuilder.cpp(828,5): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [D:\Projects\TinyORM\build\tests\auto\unit\orm\schema\mysql_schemabuilder\mysql_schemabuilder.vcxproj]
    D:\Projects\TinyORM\tests\auto\unit\orm\schema\mysql_schemabuilder\tst_mysql_schemabuilder.cpp(828,5): error C2143: syntax error: missing ',' before '&' [D:\Projects\TinyORM\build\tests\auto\unit\orm\schema\mysql_schemabuilder\mysql_schemabuilder.vcxproj]

build attempt was done on windows using SDK 10.0.19041.0 and [vcpkg fba81a6a5](https://github.com/microsoft/vcpkg/commit/fba81a6a5) which is the same as the current github actions use, though it also reproduces on very different platforms.

The missing exceptions are actually being built as part of the querybuilder. The problem instead is that the tests deep-end on `models/user.hpp` to include the header files for the exception classes they are using, but the [corresponding include directive is skipped](https://github.com/silverqx/TinyORM/blob/1cc4dd183d008a36debc73e941fa01d86d26330f/tests/auto/unit/orm/schema/mysql_schemabuilder/tst_mysql_schemabuilder.cpp#L11) for builds that disable ORM.

**Comment by silverqx** [comment] 2023-07-24 12:42
The problem is that currently, we don't have any GitHub action with disabled `ORM` and I personally don't compile with disabled `ORM` too often, last time it was a few months ago. 

Thank you for the report, it will be fixed in the next release.

**Comment by silverqx** [comment] 2023-07-24 14:27
Merged, thank you

**Closed by silverqx** 2023-07-24 14:27 UTC
Labels: bug

**Comment by silverqx** [comment] 2023-07-25 06:46
The fix is already in the `main` branch, it should be fine now.
