### ISSUE TITLE
Linker error when building with MinGW 11.2

### ISSUE THREAD

**Issue by githubuser0xFFFF** [silverqx/TinyORM#44] opened 2024-05-28 12:00 UTC
When I build TinyORM with MinGW 11.2 i get the following linker error:

```
collect2.exe: fatal error: cannot find 'ld'
```

I can fix this error by removing or commenting line 160 in `TinyCommon.cmake`: **-fuse-ld=lld**. The lld linker is not included in a normal MinGW distribution.

```cmake
    if(MINGW)
        target_compile_options(${target} INTERFACE
            $<$<CXX_COMPILER_ID:Clang,AppleClang>:-Wno-ignored-attributes>
        )

        target_link_options(${target} INTERFACE
            $<$<CONFIG:Debug,RelWithDebInfo>:
                LINKER:--dynamicbase,--high-entropy-va,--nxcompat
                LINKER:--default-image-base-high>
            # Use faster linker ( GNU ld linker doesn't work with the Clang;
            # for both GCC and Clang )
            # TODO use LINKER_TYPE target property when min. version will be CMake v3.29 silverqx
            # -fuse-ld=lld
        )
    endif()
```

**Comment by silverqx** [comment] 2024-05-28 12:03
And does it compile on mingw? I'm only using msys2.

**Comment by githubuser0xFFFF** [comment] 2024-05-28 12:38
Yes, It compiles with MinGW and if I remove the line -fuse-ld=lld it also links properly. If I build the debug version I need to completely disable this part:

```cmake
 target_link_options(${target} INTERFACE
            $<$<CONFIG:Debug,RelWithDebInfo>:
                LINKER:--dynamicbase,--high-entropy-va,--nxcompat
                LINKER:--default-image-base-high>
            # Use faster linker ( GNU ld linker doesn't work with the Clang;
            # for both GCC and Clang )
            # TODO use LINKER_TYPE target property when min. version will be CMake v3.29 silverqx
            # -fuse-ld=lld
        )
```

to link the library.

I use the MinGW distribution that is installed with the Qt installer for Qt 5.15.2. So the only problem for me is the link step.

**Comment by silverqx** [comment] 2024-05-28 12:54
I tried now mingw 11.2 with Qt 6.7.1 and I have 2 more problems, it doesn't recognize `--default-image-base-high` linker option and also doesn't recognize this pragma `#  pragma GCC diagnostic ignored "-Wdangling-reference"`.

Now I also tried MinGW 13.1 and it works with this pragma but still doesn't recognize `--default-image-base-high`.

**Comment by githubuser0xFFFF** [comment] 2024-05-28 12:59
Yes, this happens if you build with debug info - to workaround this, I simply disable / remove the following part:

```cmake
 target_link_options(${target} INTERFACE
            $<$<CONFIG:Debug,RelWithDebInfo>:
                LINKER:--dynamicbase,--high-entropy-va,--nxcompat
                LINKER:--default-image-base-high>
            # Use faster linker ( GNU ld linker doesn't work with the Clang;
            # for both GCC and Clang )
            # TODO use LINKER_TYPE target property when min. version will be CMake v3.29 silverqx
            # -fuse-ld=lld
        )
```

**Comment by silverqx** [comment] 2024-05-28 13:13
mingw64 13.1 has outdated ld.exe v2.40, the `--default-image-base-high` is already fixed in ld 2.42.

**Comment by silverqx** [comment] 2024-05-28 13:59
I have found ~7 problems:

- `--default-image-base-high`
- `#pragma GCC diagnostic ignored "-Wdangling-reference"`
- `-fuse-ld=lld`
- a build done with MinGW 13.1 finishes with 0 errors/warnings but I can't execute binaries, can't find an entry point in dll (this isn't happening with MinGW 11.2 `tom.exe`), but now I have also tried with MinGW 11.2 and the same problem with unit tests like: The procedure entry point basic_string::char_traits::replace 😮 could not be located in dyn. link library TinyOrm0d.dll, so there will be more problems with this, it can be caused by these security flags or ASLR.
- `FindMySQL.cmake` package module can't find MySQL client library on MinGW
- QtCreator cmake impl. doesn't add dll libraries on the run path with MinGW kits and I think the same problem exists for msys2?
- ld linker is soo slooow 😂

I really recommend installing MSYS2 ucrt64, mingw-w64 is only outdated msys2 that is missing many fixes.

I look at this when I will have a more time but msys2 ucrt64 g++, clang++ builds are tested using CI pipelines with all possible cmake option combinations, static/shared/tinydrivers/g++/clang++ builds, ... [here](https://github.com/silverqx/TinyORM/actions/runs/9193929586) and [here](https://github.com/silverqx/TinyORM/actions/workflows/msys2-ucrt64.yml).
I don't plan to do this for mingw-w64 at sure.

**Comment by silverqx** [comment] 2024-08-22 07:11
I have removed that hard-coded `-fuse-ld=lld` for `if(MINGW)` in c5b02a5, linker type can be changed using the [`CMAKE_LINKER_TYPE`](https://cmake.org/cmake/help/latest/variable/CMAKE_LINKER_TYPE.html) compiler definition on the cmake command line. It will be in the next release v0.38.1.

**Closed by silverqx** 2024-08-22 07:11 UTC
Labels: bug, cmake
