### ISSUE TITLE
vcpkg ports error

### ISSUE THREAD

**Issue by kunpen** [silverqx/TinyORM#10] opened 2023-03-07 02:19 UTC
PS H:\Proglib\c\vcpkg\vcpkg> .\vcpkg.exe install tinyorm  --overlay-ports="H:\Proglib\c\vcpkg\TinyORM\cmake\vcpkg\ports\tinyorm"
Computing installation plan...
libmysql[core]:x86-windows is only supported on '!(windows & x86) & !uwp'

**Comment by kunpen** [comment] 2023-03-07 02:21
how to add existed port into vcpkg？

**Comment by silverqx** [comment] 2023-03-07 09:06
Hi, this is really old code, I created it a year ago and didn't touch it since then. I didn't even remember why I also committed the libevent and libmysql ports 🫤, I think libevent and libmysql had some bugs and didn't work correctly.

The tinyorm port should work, there is not to much that can fail, the problem is if the qt5-base is going to build correctly with MySQL plugin, also Qt6 is already out, and would be much better to use it instead of Qt5.

I'm suggesting removing the libevent and libmysql ports and changing the Qt5 to Qt6 and it should work.

**Comment by silverqx** [comment] 2023-03-07 09:36
> how to add existed port into vcpkg？

When I played with it a year ago, then I copied it manually to the `vcpkg/ports/` folder.

**Comment by silverqx** [comment] 2023-03-07 14:39
I have updated the `tinyorm` port to the Qt6 version, also renamed old port to the `tinyorm-qt5`. But I'm not able to build `qt5-base` or `qtbase[sql]`, the `harfbuzz:x64-windows` package build fails 🫤 (to be exact, it builds ok, but fails during the installation step).

Currently, I'm only able to build `qtbase[core]`, but can't `qtbase[sql]` and tinyorm depends on this `sql` module.

**Closed** 2023-03-28 12:02 UTC
Labels: bug, future
